### ISSUE TITLE
collaborative

### ISSUE THREAD

**Issue by JosephBARBIERDARNAL** [JosephBARBIERDARNAL/30DayMapChallenge#1]

**Comment by JosephBARBIERDARNAL** [comment]
dir with code and outputs

https://github.com/JosephBARBIERDARNAL/30DayMapChallenge/tree/main/src/17-collaborative

**Comment by JosephBARBIERDARNAL** [comment]
I tried 2 different things. a connection map

![Screenshot 2024-11-16 at 16 34 36](https://github.com/user-attachments/assets/24daa4d3-a820-49ae-aa41-e196d26b6001)

a heatmap (left is pickup location, right dropoff, or the opposite)

![Screenshot 2024-11-16 at 16 35 08](https://github.com/user-attachments/assets/907ae9f6-268e-45d6-81fa-480b9c845596)

**Comment by JosephBARBIERDARNAL** [comment]
I think creating an animation that traces the path of each taxi over time would be a great idea, given that we have precise timestamps. However, this could take days to complete and might be too time-consuming.

I prefer the heatmap, though it still needs some adjustments (not entirely sure what yet) to really stand out.

**Comment by jesusmlb** [comment]
Nice work! I created the animation of the pickup location by hours but not quite sure about the format. Let me know what you think 

<img width="958" alt="Screenshot 2024-11-16 at 17 11 25" src="https://github.com/user-attachments/assets/ae4e02e8-2355-4c2e-a11e-5a57b54476e5">

**Comment by jesusmlb** [comment]
I create a PR for the notebook I created so you can play with it and/or improve the code

**Comment by JosephBARBIERDARNAL** [comment]
Hi @jesusmlb 
I made a few updates and merged your PR. I let you pull and tell me what you think / improve it if you want (with a new PR)

I recorded my screen to show you how it currently looks like

![heatmap](https://github.com/user-attachments/assets/866ec606-111f-4ab2-821f-1745ece3d438)

**Comment by JosephBARBIERDARNAL** [comment]
It updates every minute, though perhaps hourly updates might be more appropriate. Additionally, it seems to be capped at 10fps, which is relatively slow.

**Comment by JosephBARBIERDARNAL** [comment]
I just realized my heatmap is not a real one compared to yours. Let me fix that

**Comment by JosephBARBIERDARNAL** [comment]
I used `HeatMapWithTime` to create the animation, but the resulting "heatmap" looks a bit unusual. If you have any suggestions, feel free to give them a try!

**Comment by JosephBARBIERDARNAL** [comment]
I’m really happy with what we have so far! One question, though—should we address the fact that there are multiple days in the dataset, or is that okay as is? @jesusmlb  

If it works for you, I think we’re ready to share the final version. I try not to overthink it since I aim to stick to 1/day 😅

**Comment by jesusmlb** [comment]
Yeah, me too. I think for the purpose of the challenge is fine. We achieved what we discussed in the beginning and also collaborate to make it better in terms of visualisation.

You can share it as the final version. Thanks!

**Comment by JosephBARBIERDARNAL** [comment]
Cool! I'll tag you in my post so you'll have a notif
